---
- name: Install Firewalld and Python Firewall Bindings
  command: sudo dnf install -y firewalld python3-firewall
  args:
    creates: /usr/sbin/firewalld  # Ensures the command runs only if Firewalld isn't installed
- name: Enable and Start Firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes
    state: started
- name: Ensure Firewalld Default Zone is Set
  become: yes
  shell: firewall-cmd --get-default-zone || firewall-cmd --set-default-zone=public






