---
- name: Install Java 17 (Jenkins agent dependency)
  become: yes
  command: dnf5 install -y java-17-openjdk java-17-openjdk-devel

- name: Create Jenkins User
  become: yes
  user:
    name: jenkins
    shell: /bin/bash
    create_home: true
    home: /home/jenkins
...