---
# Main configuration tasks

# Configure Gunicorn
- name: Copy Gunicorn Service File
  template:
    src: gunicorn.service.j2
    dest: /etc/systemd/system/gunicorn.service
  notify: Restart Gunicorn

# Configure Nginx
- name: Copy Nginx Configuration (Ubuntu)
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_dir_ubuntu }}/default"
  notify: Restart Nginx
  when: ansible_distribution == "Ubuntu"

- name: Copy Nginx Configuration (CentOS)
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_config_dir_centos }}/default.conf"
  notify: Restart Nginx
  when: ansible_distribution == "CentOS"

# Set up SSL certificates
- name: Create SSL directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/ssl/private
    - /etc/ssl/certs

- name: Generate private key
  openssl_privatekey:
    path: "{{ ssl_key_path }}"
    size: 2048
    mode: 0600
  register: private_key

- name: Generate a CSR (Certificate Signing Request)
  openssl_csr:
    path: "{{ ssl_csr_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    common_name: "{{ ansible_default_ipv4.address }}"
  when: private_key.changed

- name: Generate self-signed certificate
  openssl_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    csr_path: "{{ ssl_csr_path }}"
    provider: selfsigned
    selfsigned_not_after: "+365d"
  when: private_key.changed

- name: Set up periodic certificate regeneration
  cron:
    name: "Regenerate Self-Signed Certificate"
    job: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/selfsigned.key -out /etc/ssl/certs/selfsigned.crt -subj '/CN={{ ansible_default_ipv4.address }}'"
    state: present
    special_time: monthly

