---

# Ensure app directory exists
- name: Ensure app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

# Check if source files exist
- name: Check if source files exist
  stat:
    path: "{{ src_dir }}/{{ item }}"
  loop:
    - app.py
    - init_db.js
    - requirements.txt
  register: source_files

- name: Fail if any source file is missing
  fail:
    msg: "Missing required file: {{ item.item }}"
  when: not item.stat.exists
  loop: "{{ source_files.results }}"

# Copy application files
- name: Copy application files
  copy:
    src: "{{ src_dir }}/{{ item }}"
    dest: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'
  loop:
    - app.py
    - init_db.js
    - requirements.txt

# Set up virtual environment
- name: Ensure virtual environment directory exists
  file:
    path: "{{ app_dir }}/venv"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    virtualenv: "{{ app_dir }}/venv"

# Deploy systemd service for Flask
- name: Deploy systemd service for Flask
  template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service
  notify: Restart Flask App

# Reload systemd daemon and start the service
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Start and enable Flask service
  systemd:
    name: flask_app
    state: started
    enabled: yes

