---
- name: Ensure app directory exists
  file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Copy application files
  copy:
    src: "{{ playbook_dir }}/../../src/{{ item }}"
    dest: "{{ app_dir }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0644'
  loop:
    - app.py
    - init_db.js
    - requirements.txt

- name: Create virtual environment if not exists
  command:
    cmd: python3 -m venv {{ app_dir }}/venv
    creates: "{{ app_dir }}/venv"

- name: Install Python dependencies
  pip:
    requirements: "{{ app_dir }}/requirements.txt"
    executable: pip3
    virtualenv: "{{ app_dir }}/venv"

- name: Deploy systemd service for Flask
  template:
    src: flask_app.service.j2
    dest: /etc/systemd/system/flask_app.service
  notify: Restart Flask App


