---
# Install system packages
- name: Install required packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv
    - nginx
    - certbot
    - python3-certbot-nginx

- name: Install additional packages for CentOS
  become: yes
  package:
    name: python3-virtualenv
    state: present
  when: ansible_distribution == "CentOS"

# Set up virtual environment
- name: Ensure virtual environment directory exists
  become: yes
  file:
    path: /opt/myapp/venv
    state: directory
    mode: '0755'

- name: Create a virtual environment
  become: yes
  command:
    cmd: "python3 -m venv /opt/myapp/venv"
  args:
    creates: /opt/myapp/venv/bin/activate

# Install Flask and Gunicorn
- name: Install Flask and Gunicorn using pip
  become: yes
  pip:
    name:
      - Flask
      - gunicorn
    virtualenv: /opt/myapp/venv

