---
- name: Update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: dist

#Install system packages( Python, pip,venv,nginx,gunicorn)
- name: Install required packages (Ubuntu)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv
    - nginx
    - certbot
    - gunicorn
    - python3-certbot-nginx
  when: ansible_distribution == "Ubuntu"

- name: Install required packages (RHEL/CentOS)
  become: yes # This enables privilege escalation
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-virtualenv
    - nginx
    - certbot
    - gunicorn
    - python3-certbot-nginx
  when: ansible_distribution == "CentOS"

- name: create a virtual environment
  command:
    cmd: "python3 -m venv {{ app_dir }}/venv"
    creates: "{{ app_dir }}/venv"

- name: Install Flask and Gunicorn using python3-pip
  become: yes # This enables privilege escalation
  pip:
    name:
      - Flask
      - gunicorn
    virtualenv: "{{ app_dir }}/venv"
  when: ansible_distribution in ["Ubuntu","CentOS"]