---
# Install system packages (Python, pip, venv, Nginx, Gunicorn)
- name: Install required packages (Ubuntu)
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3
    - python3-pip
    - python3-venv
    - nginx
    - certbot
    - python3-certbot-nginx
  when: ansible_distribution == "Ubuntu"

- name: Install required packages (RHEL/CentOS)
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip
    - python3-venv
    - nginx
    - certbot
    - python3-certbot-nginx
  when: ansible_distribution == "CentOS"

- name: Create a virtual environment
  command:
    cmd: "python3 -m venv /opt/myapp/venv"
    creates: /opt/myapp/venv

- name: Install Flask and Gunicorn using pip
  become: yes
  pip:
    name:
      - Flask
      - gunicorn
    virtualenv: /opt/myapp/venv
