- name: Install MongoDB
  apt:
    name: mongodb
    state: present

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Insert starter records
  mongo_db:
    login_host: localhost
    database: myapp
    collection: users
    documents:
      - { name: "Alice", role: "admin" }
      - { name: "Bob", role: "user" }