---
# Ensure verification directory exists
- name: Create directory for artifact verification
  file:
    path: "{{ app_verification_dir }}"
    state: directory
    mode: '0755'
  tags: [verify, security]

# Check if artifact and hash file exist
- name: Check if artifact exists
  stat:
    path: "{{ jenkins_artifacts_dir }}/{{ app_artifact_name }}"
  register: artifact_exists

- name: Fail if artifact is missing
  fail:
    msg: "Artifact file is missing: {{ jenkins_artifacts_dir }}/{{ app_artifact_name }}"
  when: not artifact_exists.stat.exists

- name: Check if hash file exists
  stat:
    path: "{{ jenkins_artifacts_dir }}/hash.txt"
  register: hash_file_exists

- name: Fail if hash file is missing
  fail:
    msg: "Hash file is missing: {{ jenkins_artifacts_dir }}/hash.txt"
  when: not hash_file_exists.stat.exists

# Copy artifact hash file
- name: Copy artifact hash file
  copy:
    src: "{{ jenkins_artifacts_dir }}/hash.txt"
    dest: "{{ app_verification_dir }}/hash.txt"
    mode: '0644'
  tags: [verify, security]

# Generate SHA-256 hash of deployed artifact
- name: Generate SHA-256 hash of deployed artifact
  shell: sha256sum {{ jenkins_artifacts_dir }}/{{ app_artifact_name }} | awk '{print $1}'
  register: calculated_hash
  changed_when: false
  tags: [verify, security]

# Read expected hash
- name: Read expected hash
  set_fact:
    expected_hash: "{{ lookup('file', '{{ app_verification_dir }}/hash.txt') | trim }}"
  tags: [verify, security]

# Verify artifact integrity
- name: Verify artifact integrity
  fail:
    msg: "Artifact integrity check failed! Expected: {{ expected_hash }} but calculated: {{ calculated_hash.stdout }}"
  when: calculated_hash.stdout != expected_hash
  tags: [verify, security]

# Log successful verification
- name: Log successful verification
  blockinfile:
    path: "{{ app_log_dir }}/deployment.log"
    block: |
      {{ ansible_date_time.iso8601 }} - Artifact integrity verification successful
      Artifact: {{ app_artifact_name }}
      Expected Hash: {{ expected_hash }}
      Calculated Hash: {{ calculated_hash.stdout }}
    create: yes
    mode: '0644'
  tags: [verify, security, logging]